### ISSUE TITLE
Check bài

### ISSUE THREAD

**Issue by HaiYenPham** [flower-2k/flower-2k.github.io#1]
https://github.com/flower-2k/flower-2k.github.io/blob/480ca4014b906f8af277421874e756ec98fa7967/index.html#L7

-Deadline là chủ nhật mà chiều nay em mới nộp bài tập.
-Bài tập ac đưa ra chỉ là mẫu để các em làm giống form vậy thôi (ngoại trừ những bài yêu cầu làm theo mẫu) còn em cũng nên làm bài của riêng mình... 
-Tuần sau nhớ nộp bài đúng hạn nhé!
Thân ái và quyết thắng <3

**Comment by flower-2k** [comment]
em xin lỗi anh chị vì đã k đúng hạn ạ!
lần sau em sẽ rút kinh nghiệm sâu sắc ạ!
em cảm ơn nhieuffuuuuu <3
